service: serverless-social-media-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

plugins:
  - serverless-iam-roles-per-function

functions:
  createUser:
    handler: lambda_functions/user_handler.createUser
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: post
          path: api/users

  getUser:
    handler: lambda_functions/user_handler.getUserById
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          method: get
          path: api/users/{id}

  updateUser:
    handler: lambda_functions/user_handler.updateUser
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: put
          path: api/users/{id}

  deleteUser:
    handler: lambda_functions/user_handler.deleteUser
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: delete
          path: api/users/{id}

  addFollower:
    handler: lambda_functions/follower_handler.addFollower
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: post
          path: api/users/{id}/follower

  removeFollower:
    handler: lambda_functions/follower_handler.removeFollower
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: delete
          path: api/users/{id}/follower

  getFollowers:
    handler: lambda_functions/follower_handler.getFollowers
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: get
          path: api/users/{id}/follower

  getFollowees:
    handler: lambda_functions/follower_handler.getFollowees
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: 
          - !GetAtt SSMAMainTable.Arn
          - !Sub "${SSMAMainTable.Arn}/index/InvertedIndex"
    events:
      - http:
          method: get
          path: api/users/{id}/followee

resources:
  Resources:
    SSMAMainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SSMA_Main
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: InvertedIndex
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    SSMAFeedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SSMA_Feed
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: postId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: postId
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: TimestampIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
