service: serverless-social-media-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

plugins:
  - serverless-iam-roles-per-function

functions:
  authorizer:
    handler: lambda_functions/auth_handler.authorizer    

  createUser:
    handler: lambda_functions/user_handler.createUser
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: post
          path: api/users

  getUser:
    handler: lambda_functions/user_handler.getUserById
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          method: get
          path: api/users/{userId}

  updateUser:
    handler: lambda_functions/user_handler.updateUser
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: put
          path: api/users/{userId}
          authorizer: authorizer

  deleteUser:
    handler: lambda_functions/user_handler.deleteUser
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: delete
          path: api/users/{userId}
          authorizer: authorizer

  addFollower:
    handler: lambda_functions/follower_handler.addFollower
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: post
          path: api/users/{userId}/follower
          authorizer: authorizer

  removeFollower:
    handler: lambda_functions/follower_handler.removeFollower
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: delete
          path: api/users/{userId}/follower
          authorizer: authorizer

  getFollowers:
    handler: lambda_functions/follower_handler.getFollowers
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: get
          path: api/users/{userId}/follower
          authorizer: authorizer

  getFollowees:
    handler: lambda_functions/follower_handler.getFollowees
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: 
          - !GetAtt SSMAMainTable.Arn
          - !Sub "${SSMAMainTable.Arn}/index/InvertedIndex"
    events:
      - http:
          method: get
          path: api/users/{userId}/followee
          authorizer: authorizer

  createPost:
    handler: lambda_functions/posts_handler.createPost
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: post
          path: api/users/{userId}/posts
          authorizer: authorizer

  getPost:
    handler: lambda_functions/posts_handler.getPostById
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    events:
      - http:
          method: get
          path: api/users/{userId}/posts/{postId}
          authorizer: authorizer

  updatePost:
    handler: lambda_functions/posts_handler.updatePost
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: put
          path: api/users/{userId}/posts/{postId}
          authorizer: authorizer

  deletePost:
    handler: lambda_functions/posts_handler.deletePost
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: delete
          path: api/users/{userId}/posts/{postId}
          authorizer: authorizer

  likePost:
    handler: lambda_functions/likes_handler.likePost
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:PutItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: post
          path: api/users/{userId}/posts/{postId}/like
          authorizer: authorizer

  unlikePost:
    handler: lambda_functions/likes_handler.unlikePost
    environment: 
      MAIN_TABLE: !Ref SSMAMainTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt SSMAMainTable.Arn
    events:
      - http:
          method: delete
          path: api/users/{userId}/posts/{postId}/like
          authorizer: authorizer


resources:
  Resources:
    SSMAMainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SSMA_Main
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: InvertedIndex
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: PK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    SSMAFeedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SSMA_Feed
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: postId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: postId
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: TimestampIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
